"""add_custom_error_and_holders_count

Revision ID: a42500197d58
Revises: 5e6adf8b3b02
Create Date: 2026-02-03 18:07:23.478463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a42500197d58'
down_revision: Union[str, Sequence[str], None] = '5e6adf8b3b02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('holders_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('transactions', sa.Column('gas_used', sa.BigInteger(), nullable=True))
    op.add_column('transactions', sa.Column('custom_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'custom_error')
    op.drop_column('transactions', 'gas_used')
    op.drop_column('tokens', 'holders_count')
    # ### end Alembic commands ###
