"""initial schema

Revision ID: eb87305453a8
Revises: 
Create Date: 2026-01-31 00:42:17.075328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb87305453a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('first_seen_block', sa.BigInteger(), nullable=True),
    sa.Column('is_contract', sa.Boolean(), nullable=False),
    sa.Column('balance_cached', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('address')
    )
    op.create_table('blocks',
    sa.Column('number', sa.BigInteger(), nullable=False),
    sa.Column('hash', sa.String(length=66), nullable=False),
    sa.Column('parent_hash', sa.String(length=66), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('miner', sa.String(length=42), nullable=False),
    sa.Column('gas_used', sa.BigInteger(), nullable=False),
    sa.Column('gas_limit', sa.BigInteger(), nullable=False),
    sa.Column('tx_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('number'),
    sa.UniqueConstraint('hash')
    )
    op.create_index(op.f('ix_blocks_miner'), 'blocks', ['miner'], unique=False)
    op.create_index(op.f('ix_blocks_parent_hash'), 'blocks', ['parent_hash'], unique=False)
    op.create_table('chain_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('last_block_number', sa.BigInteger(), nullable=False),
    sa.Column('last_block_hash', sa.String(length=66), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('chain_id > 0', name='ck_chain_id_positive'),
    sa.CheckConstraint('last_block_number >= 0', name='ck_last_block_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain_id')
    )
    op.create_table('contracts',
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('creator_tx', sa.String(length=66), nullable=False),
    sa.Column('creation_block', sa.BigInteger(), nullable=False),
    sa.Column('bytecode_hash', sa.String(length=66), nullable=True),
    sa.ForeignKeyConstraint(['address'], ['addresses.address'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('address')
    )
    op.create_table('transactions',
    sa.Column('hash', sa.String(length=66), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('tx_index', sa.Integer(), nullable=False),
    sa.Column('from_address', sa.String(length=42), nullable=False),
    sa.Column('to_address', sa.String(length=42), nullable=True),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.Column('gas', sa.BigInteger(), nullable=False),
    sa.Column('gas_price', sa.BigInteger(), nullable=False),
    sa.Column('input', sa.Text(), nullable=True),
    sa.Column('nonce', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.CheckConstraint('nonce >= 0', name='ck_nonce_non_negative'),
    sa.ForeignKeyConstraint(['block_number'], ['blocks.number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_index('ix_transactions_block_number_tx_index', 'transactions', ['block_number', 'tx_index'], unique=False)
    op.create_index(op.f('ix_transactions_from_address'), 'transactions', ['from_address'], unique=False)
    op.create_index(op.f('ix_transactions_to_address'), 'transactions', ['to_address'], unique=False)
    op.create_table('token_transfers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=False),
    sa.Column('block_number', sa.BigInteger(), nullable=False),
    sa.Column('token_address', sa.String(length=42), nullable=False),
    sa.Column('from_address', sa.String(length=42), nullable=False),
    sa.Column('to_address', sa.String(length=42), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['tx_hash'], ['transactions.hash'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_transfers_block_number'), 'token_transfers', ['block_number'], unique=False)
    op.create_index(op.f('ix_token_transfers_from_address'), 'token_transfers', ['from_address'], unique=False)
    op.create_index(op.f('ix_token_transfers_to_address'), 'token_transfers', ['to_address'], unique=False)
    op.create_index(op.f('ix_token_transfers_token_address'), 'token_transfers', ['token_address'], unique=False)
    op.create_index('ix_token_transfers_token_from', 'token_transfers', ['token_address', 'from_address'], unique=False)
    op.create_index('ix_token_transfers_token_to', 'token_transfers', ['token_address', 'to_address'], unique=False)
    op.create_index(op.f('ix_token_transfers_tx_hash'), 'token_transfers', ['tx_hash'], unique=False)
    op.create_table('tokens',
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('decimals', sa.Integer(), nullable=True),
    sa.Column('total_supply', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['address'], ['contracts.address'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('address')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    op.drop_index(op.f('ix_token_transfers_tx_hash'), table_name='token_transfers')
    op.drop_index('ix_token_transfers_token_to', table_name='token_transfers')
    op.drop_index('ix_token_transfers_token_from', table_name='token_transfers')
    op.drop_index(op.f('ix_token_transfers_token_address'), table_name='token_transfers')
    op.drop_index(op.f('ix_token_transfers_to_address'), table_name='token_transfers')
    op.drop_index(op.f('ix_token_transfers_from_address'), table_name='token_transfers')
    op.drop_index(op.f('ix_token_transfers_block_number'), table_name='token_transfers')
    op.drop_table('token_transfers')
    op.drop_index(op.f('ix_transactions_to_address'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_from_address'), table_name='transactions')
    op.drop_index('ix_transactions_block_number_tx_index', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('contracts')
    op.drop_table('chain_state')
    op.drop_index(op.f('ix_blocks_parent_hash'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_miner'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_table('addresses')
    # ### end Alembic commands ###
